### ISSUE TITLE
bug(node): pageres doesn't work for Node.js 11

### ISSUE THREAD

**Issue by Kristinita** [sindresorhus/pageres#344]
### 1. Summary

pageres-cli and Grunt pageres doesn't work for me at new software for December 2018. I run pageres commands → nothing occurs.

7 months ago I can run pageres with same settings.

### 2. Environment

+ Operation system:

    + Local — Windows 10 Enterprise LTSB 64-bit EN
    + Travis CI — Ubuntu 14.04.5 LTS
    + AppVeyor — Windows Server 2016

+ Node.js 11.5.0
+ grunt-cli 1.0.3
+ pageres 4.1.0
+ grunt-pageres 3.0.0

#### 3.1. pageres-cli

+ `.travis.yml`:

```yaml
language: node_js

node_js:
- node

install:
- npm install -g pageres-cli

script:
- pageres kristinita.ru 1024x768 --verbose

```

+ `appveyor.yml`:

```yaml
install:
- choco install nodejs -y
- npm install -g pageres-cli

build_script:
- pageres kristinita.ru 1024x768 --verbose

```

I get same behavior with another URLs.

#### 3.2. Grunt pageres

See [**KiraAppveyorServer branch**](https://github.com/Kristinita/SashaGruntDebugging/tree/KiraAppveyorServer) of my demo repository:

+ `.travis.yml`:

```yaml
language: node_js

node_js:
- node

install:
- npm install -g grunt-cli
- npm install

script:
- grunt --verbose

```

+ `appveyor.yml`:

```yaml
install:
- choco install nodejs -y
- npm install -g grunt-cli
- npm install

build_script:
- grunt --verbose

```

Relative URL in example. I use [**grunt-http-server**](https://www.npmjs.com/package/grunt-http-server), that will possible create it.

+ `Gruntfile.coffee`:

```coffee
module.exports = (grunt) ->

    grunt.loadNpmTasks("grunt-http-server")
    grunt.loadNpmTasks("grunt-pageres")
    grunt.initConfig
        "http-server":
            server:
                host: "0.0.0.0"
                https: true
                port: 8282
                runInBackground: true
                root: "."
        pageres:
            screenshots:
                options:
                    dest: "screenshots/"
                    sizes: [
                            "1024x768"
                            ]
                    urls: "https://127.0.0.1:8282/output/index.html"

    grunt.registerTask("default", ["http-server", "pageres"])

```

+ `output/index.html`:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Kira</title>
</head>
<body>
    Goddess
</body>
</html>

```

### 4. Expected behavior

Successful pageres-cli and Grunt pageres usage.

#### 5.1. pageres-cli:

+ [**Travis CI**](https://travis-ci.org/Kristinita/SashaGruntDebugging/builds/471371004)
+ [**AppVeyor**](https://ci.appveyor.com/project/Kristinita/sashagruntdebugging/builds/21193398)

#### 5.2. Grunt pageres

+ [**Travis CI**](https://travis-ci.org/Kristinita/SashaGruntDebugging/builds/471375766)
+ [**AppVeyor**](https://ci.appveyor.com/project/Kristinita/sashagruntdebugging/builds/21193604)

Thanks.
